import { STORIES, type Category, type Customer, type Enquiry, type Product, type Review, type Seller, type SellerStatus, type Story } from "@/data/seed";
import { loadRemote, remoteSnapshot } from "@/lib/remote";
import { appendSheetRow, updateSheetRow } from "@/lib/sheets.functions";
import { getAdminToken } from "@/lib/session";
export type { Category, Customer, Enquiry, Product, Review, Seller, SellerStatus, Story };
export const ensureData=(force=false)=>loadRemote(force);export const dataError=()=>remoteSnapshot().error;
const KEY="nammaspot.store.v1";interface Overlay{sellers:Seller[];products:Product[];enquiries:Enquiry[];reviews:Review[];customers:Customer[];statusOverrides:Record<string,SellerStatus>;reviewApprovals:Record<string,boolean>;productImages:Record<string,string>}const emptyOverlay:Overlay={sellers:[],products:[],enquiries:[],reviews:[],customers:[],statusOverrides:{},reviewApprovals:{},productImages:{}};
function readOverlay():Overlay{if(typeof window==="undefined")return emptyOverlay;try{return {...emptyOverlay,...(JSON.parse(window.localStorage.getItem(KEY)||"{}") as Overlay)}}catch{return emptyOverlay}}function writeOverlay(o:Overlay){if(typeof window!=="undefined")window.localStorage.setItem(KEY,JSON.stringify(o))}function mutate(fn:(o:Overlay)=>void){const o=readOverlay();fn(o);writeOverlay(o)}const id=(p:string)=>`${p}${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;
function report(p:Promise<{ok:boolean;error?:string}>){void p.then(r=>{if(!r.ok)console.error("NammaSpot backend write failed:",r.error)})}function add(action:"addSeller"|"addProduct"|"addCustomer"|"addEnquiry"|"addReview",row:Record<string,string|number|boolean|null>){report(appendSheetRow({data:{action,row}}))}function update(action:"updateSeller"|"updateProduct"|"updateCustomer"|"updateEnquiry"|"updateReview",row:Record<string,string|number|boolean|null>){report(updateSheetRow({data:{action,row,token:getAdminToken()}}))}
function merge<T extends{id:string}>(remote:T[],local:T[]){const m=new Map<string,T>();remote.forEach(x=>m.set(x.id,x));local.forEach(x=>m.set(x.id,{...m.get(x.id),...x} as T));return [...m.values()]}
export function allSellers(){const o=readOverlay();return merge(remoteSnapshot().sellers,o.sellers).map(s=>({...s,status:o.statusOverrides[s.id]??s.status}))}export function allProducts(){const o=readOverlay();return merge(remoteSnapshot().products,o.products).map(p=>({...p,imageUrl:o.productImages[p.id]??p.imageUrl}))}export function allEnquiries(){return merge(remoteSnapshot().enquiries,readOverlay().enquiries)}export function allReviews(){const o=readOverlay();return merge(remoteSnapshot().reviews,o.reviews).map(r=>({...r,approved:o.reviewApprovals[r.id]??r.approved}))}export function allCustomers(){return merge(remoteSnapshot().customers,readOverlay().customers)}export const categories=():Category[]=>remoteSnapshot().categories;export function stories():Story[]{const s=approvedSellers();return s.length?STORIES.map((x,i)=>({...x,sellerId:s[i%s.length]!.id})):[]}export const approvedSellers=()=>allSellers().filter(s=>s.status==="approved");export const sellerBySlug=(slug:string)=>allSellers().find(s=>s.slug===slug);export const sellerById=(id:string)=>allSellers().find(s=>s.id===id);export const categoryById=(id:string)=>categories().find(c=>c.id===id);export const categoryBySlug=(slug:string)=>categories().find(c=>c.slug===slug);export const productsBySeller=(id:string)=>allProducts().filter(p=>p.sellerId===id&&p.active);export const reviewsBySeller=(id:string)=>allReviews().filter(r=>r.sellerId===id&&r.approved);export const enquiriesBySeller=(id:string)=>allEnquiries().filter(e=>e.sellerId===id);export const storiesBySeller=(id:string)=>stories().filter(s=>s.sellerId===id);
const BASE_AREAS=["Mylapore","Adyar","Besant Nagar","T Nagar","Anna Nagar","Velachery","Kodambakkam","Villivakkam","Tambaram","Coimbatore","Madurai"];export function areas(){return Array.from(new Set([...allSellers().flatMap(s=>[s.area,s.city]).filter(Boolean),...BASE_AREAS]))}export const AREAS=BASE_AREAS;export interface SearchFilters{q?:string;category?:string;area?:string;minRating?:number;maxPrice?:number;sort?:"featured"|"rating"|"price-low"|"newest"};export function searchSellers(f:SearchFilters){const q=(f.q??"").trim().toLowerCase();let list=approvedSellers().filter(s=>{if(f.category&&categoryById(s.categoryId)?.slug!==f.category)return false;if(f.area&&s.area!==f.area&&s.city!==f.area)return false;if(f.minRating&&s.rating<f.minRating)return false;if(f.maxPrice&&s.priceFrom>f.maxPrice)return false;if(!q)return true;return [s.businessName,s.ownerName,s.tagline,s.about,s.area,s.city,s.instagram,s.tags.join(" "),categoryById(s.categoryId)?.name??"",...allProducts().filter(p=>p.sellerId===s.id).map(p=>p.name)].join(" ").toLowerCase().includes(q)});if(f.sort==="rating")list.sort((a,b)=>b.rating-a.rating);else if(f.sort==="price-low")list.sort((a,b)=>a.priceFrom-b.priceFrom);else if(f.sort==="newest")list.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));else list.sort((a,b)=>Number(b.featured)-Number(a.featured)||b.rating-a.rating);return list}
export function createEnquiry(input:Omit<Enquiry,"id"|"status"|"createdAt">):Enquiry{const e:Enquiry={...input,id:id("e_"),status:"new",createdAt:new Date().toISOString().slice(0,10)};const existing=allCustomers().find(c=>c.phone.replace(/\D/g,"")===input.phone.replace(/\D/g,""));const c=existing??{id:id("cu_"),name:input.customerName,phone:input.phone,area:"—",createdAt:e.createdAt};mutate(o=>{o.enquiries.unshift(e);if(!existing)o.customers.unshift(c)});if(!existing)add("addCustomer",{customerId:c.id,name:c.name,phone:c.phone,area:c.area,createdAt:c.createdAt});add("addEnquiry",{enquiryId:e.id,sellerId:e.sellerId,productId:e.productId??"",customerName:e.customerName,phone:e.phone,eventDate:e.eventDate,message:e.message,status:e.status,createdAt:e.createdAt});return e}
export function registerSeller(input:Pick<Seller,"businessName"|"ownerName"|"categoryId"|"area"|"city"|"instagram"|"whatsapp"|"email"|"tagline"|"about">&{priceFrom:number}):Seller{const s:Seller={...input,id:id("s_"),slug:input.businessName.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),rating:0,reviewCount:0,featured:false,status:"pending",createdAt:new Date().toISOString().slice(0,10),deliversAcrossCity:true,tags:[]};mutate(o=>o.sellers.unshift(s));add("addSeller",{sellerId:s.id,name:s.businessName,ownerName:s.ownerName,category:categoryById(s.categoryId)?.name??"",description:s.about,tagline:s.tagline,phone:s.whatsapp,whatsapp:s.whatsapp,instagram:`@${s.instagram}`,email:s.email,location:s.area,city:s.city,priceFrom:s.priceFrom,status:s.status,createdAt:s.createdAt,imageUrl:s.imageUrl??""});return s}
export function restoreSellerProfile(s:Seller){if(!allSellers().some(x=>x.id===s.id))mutate(o=>o.sellers.unshift(s))}export function addProduct(input:Omit<Product,"id"|"views"|"active">):Product{const p:Product={...input,id:id("p_"),views:0,active:true};mutate(o=>{o.products.unshift(p);if(p.imageUrl)o.productImages[p.id]=p.imageUrl});add("addProduct",{productId:p.id,sellerId:p.sellerId,name:p.name,description:p.description,price:p.price,type:p.type,unit:p.unit,category:categoryById(sellerById(p.sellerId)?.categoryId??"")?.name??"",imageUrl:p.imageUrl??""});return p}
export function setSellerStatus(sellerId:string,status:SellerStatus){if(!sellerById(sellerId))return;mutate(o=>{o.statusOverrides[sellerId]=status});update("updateSeller",{sellerId,status})}export function setReviewApproval(reviewId:string,approved:boolean){mutate(o=>{o.reviewApprovals[reviewId]=approved});update("updateReview",{reviewId,approved})}export function setSellerImage(sellerId:string,imageUrl:string){const s=sellerById(sellerId);if(!s)return;mutate(o=>{const i=o.sellers.findIndex(x=>x.id===sellerId);const n={...s,imageUrl};if(i>=0)o.sellers[i]=n;else o.sellers.unshift(n)});update("updateSeller",{sellerId,imageUrl})}export function setProductImage(productId:string,imageUrl:string){mutate(o=>{o.productImages[productId]=imageUrl});update("updateProduct",{productId,imageUrl})}export function removeProductImage(productId:string){mutate(o=>{delete o.productImages[productId]});update("updateProduct",{productId,imageUrl:""})}
/** @deprecated Customer profile pictures are intentionally disabled. */ export function setCustomerAvatar(_customerId:string,_dataUrl:string){console.warn("Customer profile pictures are disabled in NammaSpot")}
export const inr=(n:number)=>`₹${n.toLocaleString("en-IN",{maximumFractionDigits:0})}`;
