/** NammaSpot Google Apps Script backend. Required Script Properties: SHEET_ID, ADMIN_PASSWORD. */
var TABLES={sellers:{tab:"Sellers",idKey:"sellerId"},products:{tab:"Products",idKey:"productId"},categories:{tab:"Categories",idKey:"categoryId"},customers:{tab:"Customers",idKey:"customerId"},enquiries:{tab:"Enquiries",idKey:"enquiryId"},reviews:{tab:"Reviews",idKey:"reviewId"}};
var LEGACY={addSeller:{table:"sellers",mode:"create"},addProduct:{table:"products",mode:"create"},addCustomer:{table:"customers",mode:"create"},addEnquiry:{table:"enquiries",mode:"create"},addReview:{table:"reviews",mode:"create"},updateSeller:{table:"sellers",mode:"update"},updateProduct:{table:"products",mode:"update"},updateCustomer:{table:"customers",mode:"update"},updateEnquiry:{table:"enquiries",mode:"update"},updateReview:{table:"reviews",mode:"update"}};
function prop_(n){return PropertiesService.getScriptProperties().getProperty(n)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function ok_(d){return json_({success:true,data:d===undefined?null:d})}
function fail_(e){return json_({success:false,error:String(e&&e.message?e.message:e)})}
function spreadsheet_(){var id=prop_("SHEET_ID");if(!id)throw new Error("SHEET_ID script property is not set");return SpreadsheetApp.openById(id)}
function sheet_(name,keys){var ss=spreadsheet_(),sh=ss.getSheetByName(name);if(!sh){sh=ss.insertSheet(name);if(keys&&keys.length)sh.appendRow(keys)}return sh}
function headers_(sh){var n=sh.getLastColumn();return n<1?[]:sh.getRange(1,1,1,n).getValues()[0].map(function(h){return String(h).trim()})}
function ensureHeaders_(sh,keys){var cur=headers_(sh),low=cur.map(function(h){return h.toLowerCase()}),missing=[];keys.forEach(function(k){if(low.indexOf(String(k).toLowerCase())<0)missing.push(k)});if(!missing.length)return cur;sh.getRange(1,cur.length+1,1,missing.length).setValues([missing]);return cur.concat(missing)}
function rows_(name){var sh=sheet_(name,[]),v=sh.getDataRange().getValues();if(v.length<2)return[];var head=v.shift();return v.filter(function(r){return r.some(function(x){return String(x).trim()})}).map(function(r){var o={};head.forEach(function(h,i){var k=String(h).trim();if(k)o[k]=r[i] instanceof Date?Utilities.formatDate(r[i],"UTC","yyyy-MM-dd"):r[i]});return o})}
function doGet(e){try{var a=String(e&&e.parameter&&e.parameter.action||"sellers"),c=TABLES[a];if(!c)return fail_("Invalid action: "+a);return ok_(rows_(c.tab))}catch(err){return fail_(err)}}
function col_(head,key){var l=String(key).toLowerCase();for(var i=0;i<head.length;i++)if(String(head[i]).trim().toLowerCase()===l)return i;return-1}
function findRow_(sh,head,idKey,id){var c=col_(head,idKey),last=sh.getLastRow();if(c<0||last<2)return-1;var v=sh.getRange(2,c+1,last-1,1).getValues();for(var i=0;i<v.length;i++)if(String(v[i][0]).trim()===String(id).trim())return i+2;return-1}
function dataKey_(data,h){var l=String(h).trim().toLowerCase();var ks=Object.keys(data);for(var i=0;i<ks.length;i++)if(ks[i].toLowerCase()===l)return ks[i];return null}
function writeRecord_(table,mode,data){var c=TABLES[table];if(!c)throw new Error("Invalid table: "+table);if(!data||typeof data!=="object")throw new Error("Missing data");var id=data[c.idKey];if(!id)throw new Error("Missing "+c.idKey);var lock=LockService.getScriptLock();if(!lock.tryLock(20000))throw new Error("Backend is busy, please retry");try{var sh=sheet_(c.tab,Object.keys(data)),head=ensureHeaders_(sh,Object.keys(data)),row=findRow_(sh,head,c.idKey,id);if(mode==="create"&&row===-1){sh.appendRow(head.map(function(h){var k=dataKey_(data,h);return k===null?"":data[k]}));SpreadsheetApp.flush();return{id:id,created:true}}if(row===-1)throw new Error("Record not found: "+id);var range=sh.getRange(row,1,1,head.length),cur=range.getValues()[0];head.forEach(function(h,i){var k=dataKey_(data,h);if(k!==null)cur[i]=data[k]});range.setValues([cur]);SpreadsheetApp.flush();return{id:id,created:false}}finally{lock.releaseLock()}}
function sign_(message,secret){return Utilities.base64WebSafeEncode(Utilities.computeHmacSha256Signature(message,secret))}
function issueAdminToken_(){var exp=Date.now()+8*60*60*1000,msg=String(exp),sig=sign_(msg,prop_("ADMIN_PASSWORD"));return Utilities.base64WebSafeEncode(msg+"."+sig)}
function validAdminToken_(token){try{var raw=Utilities.newBlob(Utilities.base64WebSafeDecode(token)).getDataAsString(),parts=raw.split("."),exp=Number(parts[0]);if(!exp||exp<Date.now())return false;return sign_(parts[0],prop_("ADMIN_PASSWORD"))===parts[1]}catch(e){return false}}
function doPost(e){try{var body=JSON.parse(e&&e.postData&&e.postData.contents||"{}"),action=String(body.action||"");if(action==="adminLogin"){var expected=prop_("ADMIN_PASSWORD");if(!expected)return fail_("ADMIN_PASSWORD script property is not configured");if(String(body.data&&body.data.password||"")!==String(expected))return fail_("Invalid admin credentials");return ok_({authenticated:true,token:issueAdminToken_()})}
var expectedWrite=prop_("WRITE_TOKEN");if(expectedWrite&&String(body.token||"")!==expectedWrite)return fail_("Unauthorized");var table=body.table?String(body.table):null,mode=null;if(action==="create"||action==="update")mode=action;else if(LEGACY[action]){table=LEGACY[action].table;mode=LEGACY[action].mode}else return fail_("Invalid action: "+action);
if(mode==="update"&&["sellers","reviews"].indexOf(table)>=0&&!validAdminToken_(String(body.token||"")))return fail_("Admin authentication required");return ok_(writeRecord_(table,mode,body.data||{}))}catch(err){return fail_(err)}}
